
IF
	Global("Continuous_BG2_Alora","MYAREA",0)
	OR(2)
		BeenInParty("Alora")
		Exists("Alora")
	!Dead("Alora")
//	!InPartyAllowDead("Alora")
//	!InParty("Alora")
//	!InMyArea("Alora")
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		ActionOverride("Alora",ChangeAIScript("cmalora",OVERRIDE))
		SetGlobal("Continuous_BG2_Alora","MYAREA",1)
SetGlobal("CMAloraExists","MYAREA",1) // Original block variable
		ActionOverride("Alora",SetGlobal("Continuous_BG2_Alora","LOCALS",1))
		MoveGlobal("AR0702","Alora",[360.350])
		ActionOverride("Alora",Face(5))
		ApplySpellRES("bdresurr","Alora")
		SmallWait(1)
		ReallyForceSpellDeadRES("bdrejuve","Alora")
		ChangeEnemyAlly("Alora",NEUTRAL)
		ChangeSpecifics("Alora",ALLIES)
		ActionOverride("Alora",SetNumTimesTalkedTo(0))
//		ActionOverride("Alora",SetGlobal("bd_joined","locals",0)) // SoD
		ActionOverride("Alora",ChangeAIScript("THIEF4",CLASS))
//		ActionOverride("Alora",ChangeAIScript("",RACE))
//		ActionOverride("Alora",ChangeAIScript("",GENERAL))
//		ActionOverride("Alora",ChangeAIScript("",DEFAULT))
		ActionOverride("Alora",SetDialog("CMALORA"))
 // Add alora09.cre items
		GiveItemCreate("LEAT05","Alora",0,0,0)
		GiveItemCreate("BOW06","Alora",0,0,0)
		GiveItemCreate("SW1H09","Alora",0,0,0)
		GiveItemCreate("RING10","Alora",0,0,0)
		GiveItemCreate("AROW01","Alora",40,0,0)
		GiveItemCreate("AROW02","Alora",15,0,0)
		GiveItemCreate("POTN10","Alora",5,0,0)
		GiveItemCreate("POTN17","Alora",5,0,0)
		ActionOverride("Alora",SetItemFlags("LEAT05",IDENTIFIED,TRUE))
		ActionOverride("Alora",SetItemFlags("BOW06",IDENTIFIED,TRUE))
		ActionOverride("Alora",SetItemFlags("SW1H09",IDENTIFIED,TRUE))
		XEquipItem("SW1H09","Alora",SLOT_WEAPON1,EQUIP)
		XEquipItem("LEAT05","Alora",SLOT_ARMOR,EQUIP)
 // Add alora09.cre items
		SetInterrupt(TRUE)
		Continue()
END
