
IF
	Global("Continuous_RoT_Wulfg2","MYAREA",0)
	BeenInParty("F_WULFGAR")
	!Dead("F_WULFGAR")
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		ActionOverride("F_WULFGAR",ChangeAIScript("Wulfg2",OVERRIDE))
		SetGlobal("Continuous_RoT_Wulfg2","MYAREA",1)
		ActionOverride("F_WULFGAR",SetGlobal("Continuous_RoT_Wulfg2","LOCALS",1))
		MoveGlobal("AR0602","F_WULFGAR",[630.2340])
		ActionOverride("F_WULFGAR",Face(13))
		ApplySpellRES("bdresurr","F_WULFGAR")
		SmallWait(1)
		ReallyForceSpellDeadRES("bdrejuve","F_WULFGAR")
		ChangeEnemyAlly("F_WULFGAR",NEUTRAL)
		ChangeSpecifics("F_WULFGAR",ALLIES)
		ActionOverride("F_WULFGAR",SetNumTimesTalkedTo(0))
//		ActionOverride("F_WULFGAR",ChangeAIScript("",CLASS))
//		ActionOverride("F_WULFGAR",ChangeAIScript("",RACE))
//		ActionOverride("F_WULFGAR",ChangeAIScript("",GENERAL))
//		ActionOverride("F_WULFGAR",ChangeAIScript("",DEFAULT))
		ActionOverride("F_WULFGAR",SetDialog("Wulfg2"))
		SetInterrupt(TRUE)
		Continue()
END
