

// Tiax for BG2

ACTION_IF (MOD_IS_INSTALLED ~TIAX.TP2~ ~0~ AND Continuous_Tiax = 1) AND NOT (MOD_IS_INSTALLED ~Continuous_End.tp2~ 8) BEGIN

	COPY_EXISTING ~PDIALOG.2DA~ ~override~
		PRETTY_PRINT_2DA
		REPLACE_TEXTUALLY ~^Tiax .*[%newline%]*~ ~~
		REPLACE_TEXTUALLY ~^O#Tiax~ ~Tiax~
		PRETTY_PRINT_2DA
	BUT_ONLY

		COPY_EXISTING ~interdia.2DA~ ~override~
			PRETTY_PRINT_2DA
			REPLACE_TEXTUALLY ~^Tiax .*[%newline%]*~ ~~
			REPLACE_TEXTUALLY ~^O#Tiax~ ~Tiax~
			PRETTY_PRINT_2DA
		BUT_ONLY

				COPY_EXISTING ~25DIALOG.2DA~ ~override~ // Useless but we never know
					PRETTY_PRINT_2DA
					REPLACE_TEXTUALLY ~^Tiax .*[%newline%]*~ ~~
					REPLACE_TEXTUALLY ~^O#Tiax~ ~Tiax~
					PRETTY_PRINT_2DA
				BUT_ONLY

					COPY_EXISTING ~25BANTER.2DA~ ~override~ // Useless but we never know
						PRETTY_PRINT_2DA
						REPLACE_TEXTUALLY ~^Tiax .*[%newline%]*~ ~~
						REPLACE_TEXTUALLY ~^O#Tiax~ ~Tiax~
						PRETTY_PRINT_2DA
					BUT_ONLY

	COPY_EXISTING ~ITEM_USE.2DA~ ~override~ // Useless but we never know
		REPLACE_TEXTUALLY ~O#Tiax~ ~Tiax~
	BUT_ONLY

		COPY_EXISTING ~O#Tiax.cre~ ~override~
			WRITE_ASCIIE DEATHVAR ~Tiax~ (32) // Script name / Death variable
		
			COPY_EXISTING ~O#Tiax25.cre~ ~override~
				WRITE_ASCIIE DEATHVAR ~Tiax~ (32) // Script name / Death variable

		COPY_EXISTING ~AR1516.bcs~ ~override~
			DECOMPILE_AND_PATCH BEGIN
			SPRINT textToReplace ~Global("O#TiaxSpawn","GLOBAL",0)~
			COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
			PATCH_IF (num_matches > 0) BEGIN
				REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~\0
	!Exists("Tiax")
	!BeenInParty("Tiax")
	!Dead("Tiax")
	!InMyArea("Tiax")~
				PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
				PATCH_PRINT ~... // %textToReplace% found in %SOURCE_FILESPEC%
				~
			END
		END
BUT_ONLY

		COPY ~Continuous_End/Spl/Tiax_Memorised_Spell.SPL~			~override/JOTIAXCO.SPL~ // Add O#Tiax.cre spells just in case 

	EXTEND_TOP ~AR1516.bcs~ ~Continuous_End/Continuous_Baf/Continuous_Tiax.baf~ EVALUATE_BUFFER

END

