
/*

Same as Continuous_BCS.tph

*/


//                                    DLG                                           //

	COPY_EXISTING_REGEXP GLOB ~^.+\.dlg$~ ~override~
		DECOMPILE_AND_PATCH BEGIN
	// Alora BG2 START
			SPRINT textToReplace ~CreateCreature("CMALORA",\([^)]*\))~
			COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
			PATCH_IF Continuous_Alora = 2 AND (num_matches > 0) BEGIN
				REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~CreateCreature("CRE_CMALORA",\1)~
				PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
				PATCH_PRINT ~... // %textToReplace% found in %SOURCE_FILESPEC%
				~
			END
			SPRINT textToReplace ~ChangeAIScript("CMALORA",\([^)]*\))~
			COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
			PATCH_IF Continuous_Alora = 2 AND (num_matches > 0) BEGIN
				REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~ChangeAIScript("SCRIPT_CMALORA",\1)~
				PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
				PATCH_PRINT ~... // %textToReplace% found in %SOURCE_FILESPEC%
				~
			END
			SPRINT textToReplace ~StartDialog\([^)]*\)("CMALORA",\([^)]*\))~
			COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
			PATCH_IF Continuous_Alora = 2 AND (num_matches > 0) BEGIN
				REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~StartDialog\1("DIALOG_CMALORA",\2)~
				PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
				PATCH_PRINT ~... // %textToReplace% found in %SOURCE_FILESPEC%
				~
			END
			SPRINT textToReplace ~SetDialog\([^)]*\)("CMALORA")~
			COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
			PATCH_IF Continuous_Alora = 2 AND (num_matches > 0) BEGIN
				REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~SetDialog\1("DIALOG_CMALORA")~
				PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
				PATCH_PRINT ~... // %textToReplace% found in %SOURCE_FILESPEC%
				~
			END
			SPRINT textToReplace ~~~~~"CMALORA"~~~~~
			COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
			PATCH_IF Continuous_Alora = 2 AND (num_matches > 0) BEGIN
				REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~~~~~"Alora"~~~~~
				PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
				PATCH_PRINT ~... // %textToReplace% found in %SOURCE_FILESPEC%
				~
			END
			SPRINT textToReplace ~"CRE_CMALORA"~
			COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
			PATCH_IF Continuous_Alora = 2 AND (num_matches > 0) BEGIN
				REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~"CMALORA"~
				PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
				PATCH_PRINT ~... // %textToReplace% found in %SOURCE_FILESPEC%
				~
			END
			SPRINT textToReplace ~"DIALOG_CMALORA"~
			COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
			PATCH_IF Continuous_Alora = 2 AND (num_matches > 0) BEGIN
				REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~"CMALORA"~
				PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
				PATCH_PRINT ~... // %textToReplace% found in %SOURCE_FILESPEC%
				~
			END
			SPRINT textToReplace ~"SCRIPT_CMALORA"~
			COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
			PATCH_IF Continuous_Alora = 2 AND (num_matches > 0) BEGIN
				REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~"CMALORA"~
				PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
				PATCH_PRINT ~... // %textToReplace% found in %SOURCE_FILESPEC%
				~
			END
	END
	// Alora BG2 END
	// Ajantis BG2 START
			SPRINT textToReplace ~"C#Ajantis"~
			COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
			PATCH_IF Continuous_Ajantis = 2 AND (num_matches > 0) BEGIN
				REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~"Ajantis"~
				PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
				PATCH_PRINT ~... // %textToReplace% found in %SOURCE_FILESPEC%
				~
			END
	END
	// Ajantis BG2 END
	// Xan BG2 START
			SPRINT textToReplace ~CreateCreature("O#XAN",\([^)]*\))~
			COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
			PATCH_IF Continuous_Xan = 2 AND (num_matches > 0) BEGIN
				REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~CreateCreature("CRE_O#XAN",\1)~
				PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
				PATCH_PRINT ~... // %textToReplace% found in %SOURCE_FILESPEC%
				~
			END
			SPRINT textToReplace ~ChangeAIScript("O#XAN",\([^)]*\))~
			COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
			PATCH_IF Continuous_Xan = 2 AND (num_matches > 0) BEGIN
				REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~ChangeAIScript("SCRIPT_O#XAN",\1)~
				PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
				PATCH_PRINT ~... // %textToReplace% found in %SOURCE_FILESPEC%
				~
			END
			SPRINT textToReplace ~StartDialog\([^)]*\)("O#XAN",\([^)]*\))~
			COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
			PATCH_IF Continuous_Xan = 2 AND (num_matches > 0) BEGIN
				REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~StartDialog\1("DIALOG_O#XAN",\2)~
				PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
				PATCH_PRINT ~... // %textToReplace% found in %SOURCE_FILESPEC%
				~
			END
			SPRINT textToReplace ~SetDialog\([^)]*\)("O#XAN")~
			COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
			PATCH_IF Continuous_Xan = 2 AND (num_matches > 0) BEGIN
				REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~SetDialog\1("DIALOG_O#XAN")~
				PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
				PATCH_PRINT ~... // %textToReplace% found in %SOURCE_FILESPEC%
				~
			END
			SPRINT textToReplace ~PlaySound("O#XAN")~
			COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
			PATCH_IF Continuous_Xan = 2 AND (num_matches > 0) BEGIN
				REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~PlaySound("SOUND_O#XAN")~
				PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
				PATCH_PRINT ~... // %textToReplace% found in %SOURCE_FILESPEC%
				~
			END
//
			SPRINT textToReplace ~~~~~"O#XAN"~~~~~
			COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
			PATCH_IF Continuous_Xan = 2 AND (num_matches > 0) BEGIN
				REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~~~~~"Xan"~~~~~
				PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
				PATCH_PRINT ~... // %textToReplace% found in %SOURCE_FILESPEC%
				~
			END
//
			SPRINT textToReplace ~"CRE_O#XAN"~
			COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
			PATCH_IF Continuous_Xan = 2 AND (num_matches > 0) BEGIN
				REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~"O#XAN"~
				PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
				PATCH_PRINT ~... // %textToReplace% found in %SOURCE_FILESPEC%
				~
			END
			SPRINT textToReplace ~"DIALOG_O#XAN"~
			COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
			PATCH_IF Continuous_Xan = 2 AND (num_matches > 0) BEGIN
				REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~"O#XAN"~
				PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
				PATCH_PRINT ~... // %textToReplace% found in %SOURCE_FILESPEC%
				~
			END
			SPRINT textToReplace ~"SCRIPT_O#XAN"~
			COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
			PATCH_IF Continuous_Xan = 2 AND (num_matches > 0) BEGIN
				REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~"O#XAN"~
				PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
				PATCH_PRINT ~... // %textToReplace% found in %SOURCE_FILESPEC%
				~
			END
			SPRINT textToReplace ~"SOUND_O#XAN"~
			COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
			PATCH_IF Continuous_Xan = 2 AND (num_matches > 0) BEGIN
				REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~"O#XAN"~
				PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
				PATCH_PRINT ~... // %textToReplace% found in %SOURCE_FILESPEC%
				~
			END
	END
	// Xan BG2 END
	// Coran BG2 START
			SPRINT textToReplace ~CreateCreature("O#Coran",\([^)]*\))~
			COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
			PATCH_IF Continuous_Coran = 2 AND (num_matches > 0) BEGIN
				REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~CreateCreature("CRE_O#Coran",\1)~
				PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
				PATCH_PRINT ~... // %textToReplace% found in %SOURCE_FILESPEC%
				~
			END
			SPRINT textToReplace ~ChangeAIScript("O#Coran",\([^)]*\))~
			COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
			PATCH_IF Continuous_Coran = 2 AND (num_matches > 0) BEGIN
				REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~ChangeAIScript("SCRIPT_O#Coran",\1)~
				PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
				PATCH_PRINT ~... // %textToReplace% found in %SOURCE_FILESPEC%
				~
			END
			SPRINT textToReplace ~StartDialog\([^)]*\)("O#Coran",\([^)]*\))~
			COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
			PATCH_IF Continuous_Coran = 2 AND (num_matches > 0) BEGIN
				REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~StartDialog\1("DIALOG_O#Coran",\2)~
				PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
				PATCH_PRINT ~... // %textToReplace% found in %SOURCE_FILESPEC%
				~
			END
			SPRINT textToReplace ~SetDialog\([^)]*\)("O#Coran")~
			COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
			PATCH_IF Continuous_Coran = 2 AND (num_matches > 0) BEGIN
				REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~SetDialog\1("DIALOG_O#Coran")~
				PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
				PATCH_PRINT ~... // %textToReplace% found in %SOURCE_FILESPEC%
				~
			END
			SPRINT textToReplace ~PlaySound("O#Coran")~
			COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
			PATCH_IF Continuous_Coran = 2 AND (num_matches > 0) BEGIN
				REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~PlaySound("SOUND_O#Coran")~
				PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
				PATCH_PRINT ~... // %textToReplace% found in %SOURCE_FILESPEC%
				~
			END
//
			SPRINT textToReplace ~~~~~"O#Coran"~~~~~
			COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
			PATCH_IF Continuous_Coran = 2 AND (num_matches > 0) BEGIN
				REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~~~~~"Coran"~~~~~
				PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
				PATCH_PRINT ~... // %textToReplace% found in %SOURCE_FILESPEC%
				~
			END
//
			SPRINT textToReplace ~"CRE_O#Coran"~
			COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
			PATCH_IF Continuous_Coran = 2 AND (num_matches > 0) BEGIN
				REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~"O#Coran"~
				PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
				PATCH_PRINT ~... // %textToReplace% found in %SOURCE_FILESPEC%
				~
			END
			SPRINT textToReplace ~"DIALOG_O#Coran"~
			COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
			PATCH_IF Continuous_Coran = 2 AND (num_matches > 0) BEGIN
				REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~"O#Coran"~
				PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
				PATCH_PRINT ~... // %textToReplace% found in %SOURCE_FILESPEC%
				~
			END
			SPRINT textToReplace ~"SCRIPT_O#Coran"~
			COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
			PATCH_IF Continuous_Coran = 2 AND (num_matches > 0) BEGIN
				REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~"O#Coran"~
				PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
				PATCH_PRINT ~... // %textToReplace% found in %SOURCE_FILESPEC%
				~
			END
			SPRINT textToReplace ~"SOUND_O#Coran"~
			COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
			PATCH_IF Continuous_Coran = 2 AND (num_matches > 0) BEGIN
				REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~"O#Coran"~
				PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
				PATCH_PRINT ~... // %textToReplace% found in %SOURCE_FILESPEC%
				~
			END
	END
	// Coran BG2 END
	// Branwen BG2 START
			SPRINT textToReplace ~CreateCreature("O#Bran",\([^)]*\))~
			COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
			PATCH_IF Continuous_Branwen = 2 AND (num_matches > 0) BEGIN
				REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~CreateCreature("CRE_O#Bran",\1)~
				PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
				PATCH_PRINT ~... // %textToReplace% found in %SOURCE_FILESPEC%
				~
			END
			SPRINT textToReplace ~ChangeAIScript("O#Bran",\([^)]*\))~
			COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
			PATCH_IF Continuous_Branwen = 2 AND (num_matches > 0) BEGIN
				REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~ChangeAIScript("SCRIPT_O#Bran",\1)~
				PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
				PATCH_PRINT ~... // %textToReplace% found in %SOURCE_FILESPEC%
				~
			END
			SPRINT textToReplace ~StartDialog\([^)]*\)("O#Bran",\([^)]*\))~
			COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
			PATCH_IF Continuous_Branwen = 2 AND (num_matches > 0) BEGIN
				REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~StartDialog\1("DIALOG_O#Bran",\2)~
				PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
				PATCH_PRINT ~... // %textToReplace% found in %SOURCE_FILESPEC%
				~
			END
			SPRINT textToReplace ~SetDialog\([^)]*\)("O#Bran")~
			COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
			PATCH_IF Continuous_Branwen = 2 AND (num_matches > 0) BEGIN
				REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~SetDialog\1("DIALOG_O#Bran")~
				PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
				PATCH_PRINT ~... // %textToReplace% found in %SOURCE_FILESPEC%
				~
			END
			SPRINT textToReplace ~PlaySound("O#Bran")~
			COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
			PATCH_IF Continuous_Branwen = 2 AND (num_matches > 0) BEGIN
				REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~PlaySound("SOUND_O#Bran")~
				PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
				PATCH_PRINT ~... // %textToReplace% found in %SOURCE_FILESPEC%
				~
			END
//
			SPRINT textToReplace ~~~~~"O#Bran"~~~~~
			COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
			PATCH_IF Continuous_Branwen = 2 AND (num_matches > 0) BEGIN
				REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~~~~~"Branwen"~~~~~
				PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
				PATCH_PRINT ~... // %textToReplace% found in %SOURCE_FILESPEC%
				~
			END
//
			SPRINT textToReplace ~"CRE_O#Bran"~
			COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
			PATCH_IF Continuous_Branwen = 2 AND (num_matches > 0) BEGIN
				REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~"O#Bran"~
				PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
				PATCH_PRINT ~... // %textToReplace% found in %SOURCE_FILESPEC%
				~
			END
			SPRINT textToReplace ~"DIALOG_O#Bran"~
			COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
			PATCH_IF Continuous_Branwen = 2 AND (num_matches > 0) BEGIN
				REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~"O#Bran"~
				PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
				PATCH_PRINT ~... // %textToReplace% found in %SOURCE_FILESPEC%
				~
			END
			SPRINT textToReplace ~"SCRIPT_O#Bran"~
			COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
			PATCH_IF Continuous_Branwen = 2 AND (num_matches > 0) BEGIN
				REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~"O#Bran"~
				PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
				PATCH_PRINT ~... // %textToReplace% found in %SOURCE_FILESPEC%
				~
			END
			SPRINT textToReplace ~"SOUND_O#Bran"~
			COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
			PATCH_IF Continuous_Branwen = 2 AND (num_matches > 0) BEGIN
				REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~"O#Bran"~
				PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
				PATCH_PRINT ~... // %textToReplace% found in %SOURCE_FILESPEC%
				~
			END
	END
	// Branwen BG2 END
	// Walahnan BG2 Start
			SPRINT textToReplace ~~~~~"L#2WALAH"~~~~~
			COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
			PATCH_IF Continuous_Walahnan = 2 AND (num_matches > 0) BEGIN
				REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~~~~~"L#WALAH"~~~~~
				PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
				PATCH_PRINT ~... // %textToReplace% found in %SOURCE_FILESPEC%
				~
			END
	END
	// Walahnan BG2 END
	// Isra BG2 START
			SPRINT textToReplace ~TextScreen("rh#Isra2")~
			COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
			PATCH_IF Continuous_Isra = 2 AND (num_matches > 0) BEGIN
				REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~TextScreen("Text_rh#Isra2")~
				PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
				PATCH_PRINT ~... // %textToReplace% found in %SOURCE_FILESPEC%
				~
			END
			SPRINT textToReplace ~~~~~"rh#Isra2"~~~~~
			COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
			PATCH_IF Continuous_Isra = 2 AND (num_matches > 0) BEGIN
				REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~~~~~"rh#isra"~~~~~
				PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
				PATCH_PRINT ~... // %textToReplace% found in %SOURCE_FILESPEC%
				~
			END
			SPRINT textToReplace ~"Text_rh#Isra2"~
			COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
			PATCH_IF Continuous_Isra = 2 AND (num_matches > 0) BEGIN
				REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~"rh#Isra2"~
				PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
				PATCH_PRINT ~... // %textToReplace% found in %SOURCE_FILESPEC%
				~
			END
	END
	// Isra BG2 END
	// Tiax BG2 START
			SPRINT textToReplace ~CreateCreature("O#Tiax",\([^)]*\))~
			COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
			PATCH_IF Continuous_Tiax = 2 AND (num_matches > 0) BEGIN
				REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~CreateCreature("CRE_O#Tiax",\1)~
				PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
				PATCH_PRINT ~... // %textToReplace% found in %SOURCE_FILESPEC%
				~
			END
			SPRINT textToReplace ~StartDialog\([^)]*\)("O#Tiax",\([^)]*\))~
			COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
			PATCH_IF Continuous_Tiax = 2 AND (num_matches > 0) BEGIN
				REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~StartDialog\1("DIALOG_O#Tiax",\2)~
				PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
				PATCH_PRINT ~... // %textToReplace% found in %SOURCE_FILESPEC%
				~
			END
			SPRINT textToReplace ~SetDialog\([^)]*\)("O#Tiax")~
			COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
			PATCH_IF Continuous_Tiax = 2 AND (num_matches > 0) BEGIN
				REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~SetDialog\1("DIALOG_O#Tiax")~
				PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
				PATCH_PRINT ~... // %textToReplace% found in %SOURCE_FILESPEC%
				~
			END
//
			SPRINT textToReplace ~~~~~"O#Tiax"~~~~~
			COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
			PATCH_IF Continuous_Tiax = 2 AND (num_matches > 0) BEGIN
				REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~~~~~"Tiax"~~~~~
				PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
				PATCH_PRINT ~... // %textToReplace% found in %SOURCE_FILESPEC%
				~
			END
//
			SPRINT textToReplace ~"CRE_O#Tiax"~
			COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
			PATCH_IF Continuous_Tiax = 2 AND (num_matches > 0) BEGIN
				REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~"O#Tiax"~
				PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
				PATCH_PRINT ~... // %textToReplace% found in %SOURCE_FILESPEC%
				~
			END
			SPRINT textToReplace ~"DIALOG_O#Tiax"~
			COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
			PATCH_IF Continuous_Tiax = 2 AND (num_matches > 0) BEGIN
				REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~"O#Tiax"~
				PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
				PATCH_PRINT ~... // %textToReplace% found in %SOURCE_FILESPEC%
				~
			END
	END
	// Tiax BG2 END
	// Yeslick BG2 START
			SPRINT textToReplace ~~~~~"LK#YESLK"~~~~~
			COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
			PATCH_IF Continuous_Yeslick = 2 AND (num_matches > 0) BEGIN
				REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~~~~~"Yeslick"~~~~~
				PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
				PATCH_PRINT ~... // %textToReplace% found in %SOURCE_FILESPEC%
				~
			END
	END
	// Yeslick BG2 END
	// Kivan BG2 START
			SPRINT textToReplace ~CreateCreature("P#Kivan",\([^)]*\))~
			COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
			PATCH_IF Continuous_Kivan = 2 AND (num_matches > 0) BEGIN
				REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~CreateCreature("CRE_P#Kivan",\1)~
				PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
				PATCH_PRINT ~... // %textToReplace% found in %SOURCE_FILESPEC%
				~
			END
			SPRINT textToReplace ~ChangeAIScript("P#Kivan",\([^)]*\))~
			COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
			PATCH_IF Continuous_Kivan = 2 AND (num_matches > 0) BEGIN
				REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~ChangeAIScript("SCRIPT_P#Kivan",\1)~
				PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
				PATCH_PRINT ~... // %textToReplace% found in %SOURCE_FILESPEC%
				~
			END
			SPRINT textToReplace ~StartDialog\([^)]*\)("P#Kivan",\([^)]*\))~
			COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
			PATCH_IF Continuous_Kivan = 2 AND (num_matches > 0) BEGIN
				REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~StartDialog\1("DIALOG_P#Kivan",\2)~
				PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
				PATCH_PRINT ~... // %textToReplace% found in %SOURCE_FILESPEC%
				~
			END
			SPRINT textToReplace ~SetDialog\([^)]*\)("P#Kivan")~
			COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
			PATCH_IF Continuous_Kivan = 2 AND (num_matches > 0) BEGIN
				REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~SetDialog\1("DIALOG_P#Kivan")~
				PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
				PATCH_PRINT ~... // %textToReplace% found in %SOURCE_FILESPEC%
				~
			END
			SPRINT textToReplace ~PlaySound("P#Kivan")~
			COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
			PATCH_IF Continuous_Kivan = 2 AND (num_matches > 0) BEGIN
				REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~PlaySound("SOUND_P#Kivan")~
				PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
				PATCH_PRINT ~... // %textToReplace% found in %SOURCE_FILESPEC%
				~
			END
//
			SPRINT textToReplace ~~~~~"P#Kivan"~~~~~
			COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
			PATCH_IF Continuous_Kivan = 2 AND (num_matches > 0) BEGIN
				REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~~~~~"Kivan"~~~~~
				PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
				PATCH_PRINT ~... // %textToReplace% found in %SOURCE_FILESPEC%
				~
			END
//
			SPRINT textToReplace ~"CRE_P#Kivan"~
			COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
			PATCH_IF Continuous_Kivan = 2 AND (num_matches > 0) BEGIN
				REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~"P#Kivan"~
				PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
				PATCH_PRINT ~... // %textToReplace% found in %SOURCE_FILESPEC%
				~
			END
			SPRINT textToReplace ~"DIALOG_P#Kivan"~
			COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
			PATCH_IF Continuous_Kivan = 2 AND (num_matches > 0) BEGIN
				REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~"P#Kivan"~
				PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
				PATCH_PRINT ~... // %textToReplace% found in %SOURCE_FILESPEC%
				~
			END
			SPRINT textToReplace ~"SCRIPT_P#Kivan"~
			COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
			PATCH_IF Continuous_Kivan = 2 AND (num_matches > 0) BEGIN
				REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~"P#Kivan"~
				PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
				PATCH_PRINT ~... // %textToReplace% found in %SOURCE_FILESPEC%
				~
			END
			SPRINT textToReplace ~"SOUND_P#Kivan"~
			COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
			PATCH_IF Continuous_Kivan = 2 AND (num_matches > 0) BEGIN
				REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~"P#Kivan"~
				PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
				PATCH_PRINT ~... // %textToReplace% found in %SOURCE_FILESPEC%
				~
			END
	END
	// Kivan BG2 END
///////////////////////////////////////////////////////////////////////////////
// Add your block or blocks below
///////////////////////////////////////////////////////////////////////////////
// NEW MOD BG2 START
// NEW MOD BG2 END
		END
BUT_ONLY
