

// Coran for BG2

ACTION_IF (MOD_IS_INSTALLED ~CORAN.TP2~ ~0~ AND Continuous_Coran = 1) AND NOT (MOD_IS_INSTALLED ~Continuous_End.tp2~ 4) BEGIN

	COPY_EXISTING ~PDIALOG.2DA~ ~override~
		PRETTY_PRINT_2DA
		REPLACE_TEXTUALLY ~^Coran .*[%newline%]*~ ~~
		REPLACE_TEXTUALLY ~^O#Coran~ ~Coran~
		PRETTY_PRINT_2DA
	BUT_ONLY

		COPY_EXISTING ~interdia.2DA~ ~override~
			PRETTY_PRINT_2DA
			REPLACE_TEXTUALLY ~^Coran .*[%newline%]*~ ~~
			REPLACE_TEXTUALLY ~^O#Coran~ ~Coran~
			PRETTY_PRINT_2DA
		BUT_ONLY

				COPY_EXISTING ~25DIALOG.2DA~ ~override~
					PRETTY_PRINT_2DA
					REPLACE_TEXTUALLY ~^Coran .*[%newline%]*~ ~~
					REPLACE_TEXTUALLY ~^O#Coran~ ~Coran~
					PRETTY_PRINT_2DA
				BUT_ONLY

					COPY_EXISTING ~25BANTER.2DA~ ~override~
						PRETTY_PRINT_2DA
						REPLACE_TEXTUALLY ~^Coran .*[%newline%]*~ ~~
						REPLACE_TEXTUALLY ~^O#Coran~ ~Coran~
						PRETTY_PRINT_2DA
					BUT_ONLY

	COPY_EXISTING ~ITEM_USE.2DA~ ~override~
		REPLACE_TEXTUALLY ~O#Coran~ ~Coran~
	BUT_ONLY

		COPY_EXISTING ~O#Coran.cre~ ~override~
			WRITE_ASCIIE DEATHVAR ~Coran~ (32) // Script name / Death variable
		
			COPY_EXISTING ~O#Cor25.cre~ ~override~
				WRITE_ASCIIE DEATHVAR ~Coran~ (32) // Script name / Death variable

		COPY_EXISTING ~AR0020.bcs~ ~override~
			DECOMPILE_AND_PATCH BEGIN
			SPRINT textToReplace ~Global("O#CoranSpawn","GLOBAL",0)~
			COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
			PATCH_IF (num_matches > 0) BEGIN
				REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~\0
	!Exists("Coran")
	!BeenInParty("Coran")
	!Dead("Coran")
	!InMyArea("Coran")~
				PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
				PATCH_PRINT ~... // %textToReplace% found in %SOURCE_FILESPEC%
				~
			END
		END
BUT_ONLY

	EXTEND_TOP ~AR0020.bcs~ ~Continuous_End/Continuous_Baf/Continuous_Coran.baf~ EVALUATE_BUFFER

END

