

// Kivan for BG2

ACTION_IF (MOD_IS_INSTALLED ~SETUP-KIVAN.TP2~ ~100~ AND Continuous_Kivan = 1) AND NOT (MOD_IS_INSTALLED ~Continuous_End.tp2~ ~10~) BEGIN

	COPY_EXISTING ~PDIALOG.2DA~ ~override~
		PRETTY_PRINT_2DA
		REPLACE_TEXTUALLY ~^Kivan .*[%newline%]*~ ~~
		REPLACE_TEXTUALLY ~^P#Kivan~ ~Kivan~
		PRETTY_PRINT_2DA
	BUT_ONLY

		COPY_EXISTING ~interdia.2DA~ ~override~
			PRETTY_PRINT_2DA
			REPLACE_TEXTUALLY ~^Kivan .*[%newline%]*~ ~~
			REPLACE_TEXTUALLY ~^P#Kivan~ ~Kivan~
			PRETTY_PRINT_2DA
		BUT_ONLY

				COPY_EXISTING ~25DIALOG.2DA~ ~override~ // Useless but we never know
					PRETTY_PRINT_2DA
					REPLACE_TEXTUALLY ~^Kivan .*[%newline%]*~ ~~
					REPLACE_TEXTUALLY ~^P#Kivan~ ~Kivan~
					PRETTY_PRINT_2DA
				BUT_ONLY

					COPY_EXISTING ~25BANTER.2DA~ ~override~ // Useless but we never know
						PRETTY_PRINT_2DA
						REPLACE_TEXTUALLY ~^Kivan .*[%newline%]*~ ~~
						REPLACE_TEXTUALLY ~^P#Kivan~ ~Kivan~
						PRETTY_PRINT_2DA
					BUT_ONLY

	COPY_EXISTING ~ITEM_USE.2DA~ ~override~
		REPLACE_TEXTUALLY ~P#Kivan~ ~Kivan~
	BUT_ONLY

		COPY_EXISTING ~P#Kivan.cre~ ~override~
			WRITE_ASCIIE DEATHVAR ~Kivan~ (32) // Script name / Death variable

/*
			COPY_EXISTING ~.cre~ ~override~
				WRITE_ASCIIE DEATHVAR ~Kivan~ (32) // Script name / Death variable
*/

		COPY_EXISTING ~AR0700.bcs~ ~override~
						 ~AR0703.bcs~ ~override~
			DECOMPILE_AND_PATCH BEGIN
			SPRINT textToReplace ~!Exists("Kivan")~
			COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
			PATCH_IF (num_matches > 0) BEGIN
				REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~!Exists("Kivan")
	!BeenInParty("Kivan")
	!Dead("Kivan")
	!InMyArea("Kivan")~
				PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
				PATCH_PRINT ~... // %textToReplace% found in %SOURCE_FILESPEC%
				~
			END
		END
BUT_ONLY

	OUTER_SPRINT "Kivan_LOC" "2192.2128"

	OUTER_SPRINT "Kivan_ARE" "AR0700"

		EXTEND_TOP ~AR0700.bcs~ ~Continuous_End/Continuous_Baf/Continuous_Kivan.baf~ EVALUATE_BUFFER

	OUTER_SPRINT "Kivan_LOC" "427.416"

	OUTER_SPRINT "Kivan_ARE" "AR0703"

		EXTEND_TOP ~AR0703.bcs~ ~Continuous_End/Continuous_Baf/Continuous_Kivan.baf~ EVALUATE_BUFFER

	EXTEND_TOP ~P#KIV01.bcs~ ~Continuous_End/Continuous_Baf/Continuous_Kivan_XP.baf~ EVALUATE_BUFFER

END
