

// Xan for BG2

ACTION_IF (MOD_IS_INSTALLED ~XAN.TP2~ ~0~ AND Continuous_Xan = 1) AND NOT (MOD_IS_INSTALLED ~Continuous_End.tp2~ ~3~) BEGIN

	COPY_EXISTING ~PDIALOG.2DA~ ~override~
		PRETTY_PRINT_2DA
		REPLACE_TEXTUALLY ~^Xan .*[%newline%]*~ ~~
		REPLACE_TEXTUALLY ~^O#XAN~ ~Xan~
		PRETTY_PRINT_2DA
	BUT_ONLY

		COPY_EXISTING ~interdia.2DA~ ~override~
			PRETTY_PRINT_2DA
			REPLACE_TEXTUALLY ~^Xan .*[%newline%]*~ ~~
			REPLACE_TEXTUALLY ~^O#XAN~ ~Xan~
			PRETTY_PRINT_2DA
		BUT_ONLY

				COPY_EXISTING ~25DIALOG.2DA~ ~override~ // Useless but we never know
					PRETTY_PRINT_2DA
					REPLACE_TEXTUALLY ~^Xan .*[%newline%]*~ ~~
					REPLACE_TEXTUALLY ~^O#XAN~ ~Xan~
					PRETTY_PRINT_2DA
				BUT_ONLY

					COPY_EXISTING ~25BANTER.2DA~ ~override~ // Useless but we never know
						PRETTY_PRINT_2DA
						REPLACE_TEXTUALLY ~^Xan .*[%newline%]*~ ~~
						REPLACE_TEXTUALLY ~^O#XAN~ ~Xan~
						PRETTY_PRINT_2DA
					BUT_ONLY

	COPY_EXISTING ~ITEM_USE.2DA~ ~override~
		REPLACE_TEXTUALLY ~O#XAN~ ~Xan~
	BUT_ONLY

		COPY_EXISTING ~O#Xan09.cre~ ~override~
			WRITE_ASCIIE DEATHVAR ~Xan~ (32) // Script name / Death variable
		
			COPY_EXISTING ~O#Xan25.cre~ ~override~
				WRITE_ASCIIE DEATHVAR ~Xan~ (32) // Script name / Death variable

		COPY_EXISTING ~AR1000.bcs~ ~override~
			DECOMPILE_AND_PATCH BEGIN
			SPRINT textToReplace ~Global("O#XanSpawned","GLOBAL",0)~
			COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
			PATCH_IF (num_matches > 0) BEGIN
				REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~\0
	!Exists("Xan")
	!BeenInParty("Xan")
	!Dead("Xan")
	!InMyArea("Xan")~
				PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
				PATCH_PRINT ~... // %textToReplace% found in %SOURCE_FILESPEC%
				~
			END
		END
BUT_ONLY

		COPY ~Continuous_End/Spl/Xan_Memorised_Spell.SPL~			~override/JOXanCO.SPL~ // Add O#Xan09.cre spells just in case 

	EXTEND_TOP ~AR1000.bcs~ ~Continuous_End/Continuous_Baf/Continuous_Xan.baf~ EVALUATE_BUFFER

	EXTEND_TOP ~O#XAN25S.bcs~ ~Continuous_End/Continuous_Baf/Continuous_Xan_XP.baf~ EVALUATE_BUFFER
/*
		COPY_EXISTING ~O#Drm1a.bcs~ ~override~
			DECOMPILE_AND_PATCH BEGIN
			SPRINT textToReplace ~True()~
			COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
			PATCH_IF (num_matches > 0) BEGIN
				REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~
	!Exists("Xan")
	!BeenInParty("Xan")
	!Dead("Xan")
	!InMyArea("Xan")~
				PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
				PATCH_PRINT ~... // %textToReplace% found in %SOURCE_FILESPEC%
				~
			END
		END
BUT_ONLY

	EXTEND_BOTTOM ~O#Drm1a.bcs~ ~Continuous_End/Continuous_Baf/Continuous_Xan_O#Drm1a.baf~ EVALUATE_BUFFER

		COPY_EXISTING ~O#Drm2a.bcs~ ~override~
			DECOMPILE_AND_PATCH BEGIN
			SPRINT textToReplace ~True()~
			COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
			PATCH_IF (num_matches > 0) BEGIN
				REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~
	!Exists("Xan")
	!BeenInParty("Xan")
	!Dead("Xan")
	!InMyArea("Xan")~
				PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
				PATCH_PRINT ~... // %textToReplace% found in %SOURCE_FILESPEC%
				~
			END
		END
BUT_ONLY

	EXTEND_BOTTOM ~O#Drm2a.bcs~ ~Continuous_End/Continuous_Baf/Continuous_Xan_O#Drm2a.baf~ EVALUATE_BUFFER

		COPY_EXISTING ~O#Drm3a.bcs~ ~override~
			DECOMPILE_AND_PATCH BEGIN
			SPRINT textToReplace ~True()~
			COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
			PATCH_IF (num_matches > 0) BEGIN
				REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~
	!Exists("Xan")
	!BeenInParty("Xan")
	!Dead("Xan")
	!InMyArea("Xan")~
				PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
				PATCH_PRINT ~... // %textToReplace% found in %SOURCE_FILESPEC%
				~
			END
		END
BUT_ONLY

	EXTEND_BOTTOM ~O#Drm3a.bcs~ ~Continuous_End/Continuous_Baf/Continuous_Xan_O#Drm3a.baf~ EVALUATE_BUFFER
*/
END
