

// Ajantis for BG2

ACTION_IF (MOD_IS_INSTALLED ~AJANTISBG2.TP2~ ~0~ AND NOT Continuous_Ajantis = 0) AND NOT (MOD_IS_INSTALLED ~Continuous_End.tp2~ 2) BEGIN

PRINT ~Installation of Continuous_Ajantis...

~

	COPY_EXISTING ~PDIALOG.2DA~ ~override~
		PRETTY_PRINT_2DA
		REPLACE_TEXTUALLY ~^Ajantis .*[%newline%]*~ ~~
		REPLACE_TEXTUALLY ~^C#Ajantis~ ~Ajantis~
		PRETTY_PRINT_2DA
	BUT_ONLY

		COPY_EXISTING ~interdia.2DA~ ~override~
			PRETTY_PRINT_2DA
			REPLACE_TEXTUALLY ~^Ajantis .*[%newline%]*~ ~~
			REPLACE_TEXTUALLY ~^C#Ajantis~ ~Ajantis~
			PRETTY_PRINT_2DA
		BUT_ONLY

				COPY_EXISTING ~25DIALOG.2DA~ ~override~ // Useless but we never know
					PRETTY_PRINT_2DA
					REPLACE_TEXTUALLY ~^Ajantis .*[%newline%]*~ ~~
					REPLACE_TEXTUALLY ~^C#Ajantis~ ~Ajantis~
					PRETTY_PRINT_2DA
				BUT_ONLY

					COPY_EXISTING ~25BANTER.2DA~ ~override~ // Useless but we never know
						PRETTY_PRINT_2DA
						REPLACE_TEXTUALLY ~^Ajantis .*[%newline%]*~ ~~
						REPLACE_TEXTUALLY ~^C#Ajantis~ ~Ajantis~
						PRETTY_PRINT_2DA
					BUT_ONLY

	COPY_EXISTING ~ITEM_USE.2DA~ ~override~ // Useless but we never know
		REPLACE_TEXTUALLY ~C#Ajantis~ ~Ajantis~
	BUT_ONLY

		COPY_EXISTING ~C#Ajan08.cre~ ~override~
			WRITE_ASCIIE DEATHVAR ~Ajantis~ (32) // Script name / Death variable
		
			COPY_EXISTING ~c#ajatob.cre~ ~override~
				WRITE_ASCIIE DEATHVAR ~Ajantis~ (32) // Script name / Death variable
		
		COPY_EXISTING ~c#ajcu00.bcs~ ~override~
			DECOMPILE_AND_PATCH BEGIN
			SPRINT textToReplace ~True()~
			COUNT_REGEXP_INSTANCES ~%textToReplace%~ num_matches
			PATCH_IF (num_matches > 0) BEGIN
				REPLACE_TEXTUALLY CASE_INSENSITIVE ~%textToReplace%~ ~!BeenInParty("Ajantis")~
				PATCH_PRINT ~Patching: %num_matches% matches found in %SOURCE_FILESPEC% for REPLACE_TEXTUALLY: %textToReplace%~
				PATCH_PRINT ~... // %textToReplace% found in %SOURCE_FILESPEC%
				~
			END
		END
BUT_ONLY

	EXTEND_BOTTOM ~c#ajcu00.bcs~ ~Continuous_End/Continuous_Baf/Continuous_Ajantis_c#ajcu00.baf~ EVALUATE_BUFFER

END

